### ISSUE TITLE
Lässt sich nicht kompilieren

### ISSUE THREAD

**Issue by nhhop** [InnuendoPi/MQTTDevice2#1]
> exit status 1
> 'updateSys' was not declared in this scope

>exit status 1
>'startHTTPUpdate' was not declared in this scope

Wenn ich die Teile auskommentiere läuft alles durch.
Die scheint irgendwie vergessen worden zu sein.

**Comment by InnuendoPi** [comment]
korrekt, WebUpdate ist nicht im repository enthalten
