### ISSUE TITLE
Sonoff

### ISSUE THREAD

**Issue by arcidodo** [InnuendoPi/MQTTDevice2#2]
Hi,

I use for my fermenter chamber an sonoff dual R2 to control the heating/chilling and 2 ds18b20 probe but the chip on the sonoff is an esp8285 the size is 1MB is it possible to flash this software on it? or is the firmware to big? 

https://www.itead.cc/wiki/Sonoff_Dual

greetings Arco

**Comment by InnuendoPi** [comment]
ESP8266 4MB+ required
